site_name: Anaconda  and R Installation Guide
repo_url: https://github.com/ongzhongfei/installer_guide
# edit_uri: 
nav:
    - 'index.md'
    - 'anaconda.md'
    - 'python.md'
    - 'r.md'
    - 'Running IDE.md'

theme: 
  name: readthedocs
  favicon: img/favicon.ico
  # palette:
  #   scheme: slate
# docs_dir: Main page